name: Docker CI pipeline
run-name: ${{ github.actor }} is running Docker CI pipeline
on: [push]
jobs:
  docker-ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/chechout@v4

       - name: Login to Docker Hub
         uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
        - name: DOCKER BUILD
          - run: docker build -t hanish1103k/my-flask-app .
      
        - name: Docker push
          - run: docker push hanish1103k/my-flask-app
